version: "3.9"
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docgen
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/docgen
      PORT: 8080
      STORAGE_DIR: /app/storage
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./backend/storage:/app/storage
volumes:
  dbdata:
